# Generated by Django 4.2.4 on 2023-08-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='home.category'),
            preserve_default=False,
        ),
    ]
